const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..');const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const files=['questions.json','derived-questions.json',...Array.from({length:5},(_,i)=>`expansion-2026-batch-0${i+1}.json`),'validated-2026.json','imported-exams-2026.json','imported-deposit-2026.json','imported-authorization-2026.json'];
const bank=files.flatMap(f=>read(`data/${f}`));const eligible=bank.filter(q=>['active','verified'].includes(q.status));
test('authorization cases carry precise legal evidence and never duplicate the source appendix',()=>{
 const questions=read('data/imported-authorization-2026.json');const source=read('reports/authorization-source-review.json');const proof=new Map(read('reports/authorization-legal-evidence-2026.json').questions.map(q=>[q.id,q]));
 assert.equal(questions.length,20);assert.equal(source.questions.length,31);
 for(const q of questions){assert.equal(q.source.id,source.sourceId);assert.equal(q.status,'active');assert.match(q.question.variants[0],/^Tháng 10\/2026:/);assert.match(q.explanation,/Gợi ý làm bài:/);assert.ok(source.questions.some(s=>s.adaptedQuestionIds.includes(q.id)),q.id);assert.deepEqual(proof.get(q.id).provisions.map(p=>p.reference),q.legalBasis);assert.ok(proof.get(q.id).provisions.every(p=>p.evidenceExcerpt.length>100));}
 const appendix=source.questions.filter(s=>s.id.startsWith('AUTH-SRC-4.'));assert.equal(appendix.length,7);assert.ok(appendix.every(s=>s.decision==='duplicate_source_review'&&s.adaptedQuestionIds.length===0));
});
test('all stored IDs and answer IDs are unique; single questions have exactly one key',()=>{assert.equal(new Set(bank.map(q=>q.id)).size,bank.length);for(const q of bank){assert.equal(new Set(q.answers.map(a=>a.id)).size,q.answers.length,q.id);if(q.type==='single')assert.equal(q.answers.filter(a=>a.correct===true).length,1,q.id);}});
test('eligible questions have distinct stems, explanations, registered sources and dated future law',()=>{const seen=new Set();const sources=new Set(read('data/question-sources.json').sources.map(s=>s.id));for(const q of eligible){assert.ok(q.explanation.length>=100,q.id);assert.ok(q.legalBasis.length,q.id);assert.ok(sources.has(q.source.id),q.id);assert.match(q.lastVerified,/^2026-10-05$/,q.id);assert.ok(q.difficulty&&q.questionForm,q.id);for(const v of q.question.variants){const key=v.toLocaleLowerCase('vi').replace(/[^\p{L}\p{N}]+/gu,' ').trim();assert.ok(!seen.has(key),q.id);seen.add(key);if(JSON.stringify(q.legalBasis).includes('04/2026/QH16'))assert.match(v,/2027|hiệu lực từ|có hiệu lực|thông qua|chuyển tiếp/i,q.id);}}});
test('new cases each carry traceable article evidence and precise references',()=>{const evidence=read('reports/legal-evidence-2026.json');const rows=new Map(evidence.questions.map(q=>[q.id,q]));for(const q of read('data/validated-2026.json')){assert.ok(q.question.variants.every(v=>v.startsWith('Tháng 10/2026:')),q.id);const e=rows.get(q.id);assert.ok(e,q.id);assert.equal(e.provisions.length,q.legalBasis.length,q.id);q.legalBasis.forEach((b,i)=>{assert.match(b.article,/^Điều \d+/);assert.match(b.url,/^https:\/\//);assert.deepEqual(e.provisions[i].reference,b,q.id);assert.ok(e.provisions[i].evidenceExcerpt.length>100,q.id);});}});
test('mechanical expansion cannot enter practice or exams',()=>{for(const q of bank.filter(q=>q.id.startsWith('EXP26-'))){assert.equal(q.status,'archived',q.id);assert.equal(q.lastVerified,null,q.id);assert.equal(q.audit.reason,'mechanical_paraphrase',q.id);}});

test('deposit cases have article evidence and linked source provenance; appendix stays review',()=>{
 const questions=read('data/imported-deposit-2026.json');const proof=new Map(read('reports/deposit-legal-evidence-2026.json').questions.map(q=>[q.id,q]));const source=read('reports/deposit-source-review.json');
 assert.equal(source.questions.length,25);assert.equal(questions.length,18);
 for(const q of questions){assert.equal(q.source.id,source.sourceId);assert.equal(q.part,2);assert.match(q.question.variants[0],/^Tháng 10\/2026:/);assert.match(q.explanation,/Gợi ý làm bài:/);assert.ok(source.questions.some(s=>s.adaptedQuestionIds.includes(q.id)),q.id);assert.deepEqual(proof.get(q.id).provisions.map(p=>p.reference),q.legalBasis);assert.ok(proof.get(q.id).provisions.every(p=>p.evidenceExcerpt.length>100));}
 assert.ok(source.questions.filter(s=>s.id.includes('APP')).every(s=>s.decision==='review'&&s.adaptedQuestionIds.length===0));
});

test('imported exams preserve every source item and certify only linked adapted questions',()=>{
 const source=read('reports/exam-source-review.json');const imported=read('data/imported-exams-2026.json');const evidence=new Map(read('reports/exam-legal-evidence-2026.json').questions.map(q=>[q.id,q]));const origins=new Map(source.questions.map(q=>[q.id,q]));
 assert.equal(source.questions.length,151);assert.equal(new Set(source.questions.map(q=>q.id)).size,151);assert.equal(source.questions.filter(q=>q.sourceDocument==='Đề tháng 9/2024').length,50);assert.equal(source.questions.filter(q=>q.sourceDocument!=='Đề tháng 9/2024').length,101);
 for(const q of imported){const original=origins.get(q.id);assert.ok(original,q.id);assert.match(original.sourceSha256,/^[a-f0-9]{64}$/);assert.ok(original.originalBlock,q.id);assert.ok([1,2].includes(q.part),q.id);assert.equal(q.source.questionNumber,original.sourceQuestionNumber);assert.equal(q.source.type,'user-provided');assert.deepEqual(evidence.get(q.id).provisions.map(p=>p.reference),q.legalBasis);assert.ok(evidence.get(q.id).provisions.every(p=>p.evidenceExcerpt.length>100));assert.match(q.explanation,/Gợi ý làm bài:/);if(q.status==='active')assert.equal(original.decision,'adapted_active');else {assert.equal(q.status,'archived');assert.equal(original.decision,'duplicate_bank');}}
 for(const original of source.questions.filter(q=>q.decision==='review'))assert.ok(!imported.some(q=>q.id===original.id&&q.status==='active'),original.id);
});
